### ISSUE TITLE
Forbidden (403) CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by linhvv12** [kiwitcms/github-app#63]
I have problem with kiwitcms when login account with error as below: 
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.

![image](https://user-images.githubusercontent.com/67578506/203697616-634d0fb7-6176-41b8-a07d-32586e402ccb.png)

**Comment by atodorov** [comment]
Nothing actionable here plus general login issues belong in kiwitcms/Kiwi, not here.
